# .pre-commit-config.yaml
exclude: '.patch$'
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0  # this is optional, use `pre-commit autoupdate` to get the latest rev!
    hooks:
    -   id: end-of-file-fixer
    -   id: trailing-whitespace
